### ISSUE TITLE
Debugging Widgets

### ISSUE THREAD

**Issue by paulswithers** [icstechsales/icec-widgets-starter#1]
Thank you for this project, it's extremely useful. Is there a way to debug widgets from VS Code during development? The debugger just seems to be able to access the files in the src/server folder, not those in src/widgets. If I try to add a breakpoint to a widget, I get "Breakpoint set but not yet bound", presumably because the server isn't using those files, instead it's using the compiled versions in build/public. Looking at the ngrok output on the terminal, it looks like it's just going to the compiled version, not the source code.

I'm not particularly experienced in node development, but I tried some other debug configurations and seeing if the widgets were started as a separate process, but it doesn't look like they are.

Is there a way to connect a debugger or debug the source code? If not, I'll continue to use console logging, but being able to debug would be nicer.

**Comment by dprosper** [comment]
@paulswithers When you run the `build` task from one of the templates, the script actually builds two versions, one is the development version where the code is not uglified, etc.., that code is stored under the build folder and the other version is the uglified, etc... that is stored under the dist folder.   

I typically use the build version to debug, but I always debug using the browser, i.e. place the breakpoint in the browser dev console.  I have never tried debugging with VS Code, although I have seen recordings of other developers doing it (so you might want to search on the VS Code page for more info on that).  One issue that I have ran into in the past is I have to load the script, insert the breakpoint and refresh the page using the cached js files. 

The other consideration, unless your widget is dependent on other things coming from the ICEC page, you can test the widget independently by accessing in directly in your browser.  This may make it easier to debug.  

Which one of the templates are you using?  I can give it a try and confirm it works as expeted.

**Comment by dprosper** [comment]
one update from above, the source is available under webpack folder in the dev console. That is where you can see the source and add your breakpoints.  

![image](https://user-images.githubusercontent.com/11874942/51343747-0fc37e80-1a65-11e9-8d8e-8d1e42247c65.png)

**Comment by paulswithers** [comment]
Thanks, debugging from the sources in Chrome works and allows inspection from console. I was trying to debug a new widget based on MyCommunities. All the widgets in the lab work great.
