### ISSUE TITLE
Skip ngrok?

### ISSUE THREAD

**Issue by kolomu** [icstechsales/icec-widgets-starter#2]
Is it necessary to install ngrok? I have troubles with it because it wants to download separate files and i'm behind a corporate proxy.

Is it possible to use widget-starter set without ngrok? Express server should be enough for me. 

Or for what reason do you use Ngrok?

And thank you very much for the repository and the website explaining ICEC customizing. :+1:  :)

**Comment by dprosper** [comment]
@kolomu ngrok is not a requirement, it is only there to facilitate iterating through various version of your widget during development without having to redeploy the widget each time to the Connections server.  

I would like to make a few things clear, there are two scripts for building the widgets: 

- `buildDev` script: leverages the ngrok/https server to talk to the Connections server, so your widget does not need to reside on the Connections server during testing.
- `buildProd`  script: does not require ngrok/https, however you would be required to deploy the widget to the Connections server every time you make an update and want to test it.  

You can comment out the sections for ngrok.  But if you plan on using the buildDev scripts for the widgets two things you will need to do:

1.  If using the Express server, you will need to configure it for https if talking to Connections Cloud and you will need to expose its address to the Internet.  If you are using a onPrem Connections server, then https may not be a requirement for your environment, and you should not need to expose it to the Internet.  (in this repo that is the function of ngrok) 

2. The templates provided are tightly integrated to the usage of ngrok, and if you are trying to use the development build, you will need to make changes there as well:

- the server start script generates an ngrok.json file which contains the https address of the ngrok server, this is the address that the Connections server will use to talk to your widget during a development (`buildDev`) build. 

- the templates all have a `buildDev` script, which in turns references the above ngrok.json to obtain the https address of the ngrok server and insert it into the `index.html` or `<widgetname>.html`, the actual code for that is found inside the webpack.config.js file. So you will also need to modify that file to point to server of your choice, i.e. Express or other. 

I am glad you found the site useful.  Let me know if this satisfies your inquiry and can close this issue.  I will close it either way in 1 week if I don't receive any other feedback. 

Happy coding !!

**Comment by kolomu** [comment]
Thanks for the fast and elaborate reply. 
We are not using the ICEC in the cloud and therefor don't need ngrok.

I successfully changed the buildProd / buildDev script for expressjs. All is working great now.

**Comment by norequest** [comment]
ngrok.json  generates empty file and on npm run start the following ngrok url is undefined. what should i do?
