### ISSUE TITLE
registerCustomWidget with EditorOptions-Object instead of Editor-Function

### ISSUE THREAD

**Issue by kolomu** [icstechsales/icec-widgets-starter#4]
Hello, I would like to use the second method for creating widget via the EditorOptions object.

The reason for that is that I want to utilize the "contentStream" features like selecting a community and read a blog post from that etc.

With the EditorOptions I just have to use the "channel" property. With that it is possible to get the required information.

However my problem is currently that it doesn't work like that.
When I provide an object, the getDefaultEntry(cs) Function in the XCC-Editor-CreateContentForm.js file is called. 

This function ask the contentStream for the property "entry". However that property is not available. Because the contentStream Object which gets provided is empty. And the contentStream property gets fetched from the widget not the editorOptions-Object. So I don't  know how to continue from here...

My current work-around is reloading the page. This will fix the issue somehow but I can't deploy something like that to productive environment, where you have to reload the page everytime you create a new widget. 

Do you know how to create a widget with the editorOptions object?

If not how is it possible to simulate the same behaviour like selecting a community without recoding everything? (For the editor-function approach)

Best regards and have a nice week :)

**Comment by dprosper** [comment]
I understand the issue here, but I would need to investigate.  This will take a few days before I can look into it however, it sounds like you might be at a roadblock in your project.  I suggest opening a support ticket with IBM on it asking for the same question in the meantime.  

Leave this issue open and I will report back what uncover once I carve out the time to research into it.

**Comment by kolomu** [comment]
Thanks for your fast answer. 
I found a solution which is alright for me.

In the custom widget file you have to add the following if you want to use contentStreams: (Important parts are in the contentFn which I call in custom.js to render the widget)

```javascript
(function($, W) {
  'use strict';

  /**
   * called when the Widget is rendered.
   * @param  {[jQuery Object]} container$ [the HTML container in the Widget.. ]
   * @param  {[Object]} widgetData [The widget data]
   **/
  function contentFn(container$, widgetData) {
    if (!widgetData.contentStream) {
      widgetData.contentStream = [{
        entry: {}
      }];
   }

var editor = {};

  // this defines the above functions so they can be called from custom.js
  XCC.define([], function() {
    return {
      content: contentFn,
      editor: editor
    };
  });
```
